name: "Create Infrastructure"
run-name: "${{ github.actor }} triggered infrastructure creation on ${{ github.ref_name }} via ${{ github.event_name }}"

on:
  push:
  workflow_dispatch:
    inputs:
      Environment:
        description: "Select the environment to deploy to"
        required: true
        type: choice
        default: "dev"
        options:
          - dev
          - test
      Apply:
        description: "Apply the Terraform"
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: "Terraform Workflow"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.Environment || 'dev' }}
    env:
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.1
      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init --backend-config="resource_group_name=${{ vars.AZURE_RESOURCE_GROUP }}" --backend-config="storage_account_name=${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}" --backend-config="container_name=${{ vars.AZURE_CONTAINER_NAME }}" --backend-config="key=terraform${{github.event.inputs.Environment||'dev'}}.tfstate" --backend-config="subscription_id=${{ vars.AZURE_SUBSCRIPTION_ID }}" --backend-config="tenant_id=${{ vars.AZURE_TENANT_ID }}"

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file="configs/${{ github.event.inputs.Environment || 'dev' }}-configs.tfvars"
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Terraform Apply
        if: ${{ github.event.inputs.Apply == 'true' }}
        run: terraform apply -auto-approve tfplan
